- LICENSE
- Readme.md
With this change I intend to improve automatic license detection and ratings of the repository once it's public again.
Please take extra care reviewing the license holder name.
> feature: create license file

- .github/pull_request_template.md
With this change I intend to help standardize the pull requests for easier review.
Please take extra care reviewing the included branch naming schema.
This is adapted from my project, see this only as a starting point please.
> feature: create pull request template

- .github/workflows/codeql.yml
- package-lock.json
With this change I intend to add some security scanning:
- cron job weekly
- on push to main
- on pull request to main
Please take extra care reviewing that the package.json requires node 14, we should likely update that both there and here to 20.
This is a basic setup without any advanced features and will only scan for security issues so far.
> feature: setup security scanning

- .github/workflows/pull-request-size.yml
With this change I intend to force pull requests to be small enough to review easily.
Please take extra care reviewing the max sizes provided:
- 350 additions or deletions
- totaling up to 500 lines
- package-lock.jsons are ignored
This is a direct import from idrinth-api-bench with just a few branch name changes. Depending on how this develops, we may need to change the size expectations.
> feature: add pr size check

- .github/prace.yml
- .github/workflows/prace.yml
With this change I intend to make sure people follow the guidelines.
> feature: configure prace to check branch name

- .github/workflows/greetings.yml
With this change I intend to give new contributors and users a friendly welcome to increase the chances of them being happy.
Please take extra care reviewing the proposed response time of 48h to issues,
I've gotten pretty good feedback for this on idrinth-api-bench, since there is a direct reaction.
> feature: enable greeting for first time users

- .github/workflows/eslint.yml
With this change I intend to enforce our coding standards.
> feature: enable linting in ci

- .github/workflows/test.yml
With this change I intend to enable unit testing for all pull requests.
This is currently the github default workflow.
> feature: enable unit testing

- package-lock.json
- src/app/package-lock.json
- src/app/package.json
- src/app/src/components/Home/Challenges.tsx
- src/app/src/components/Home/Header.tsx
- src/app/src/components/Home/HomePage.tsx
- src/app/src/components/Home/Sources.tsx
- src/app/src/layouts/PublicLayout.tsx
Take a look and check out the responsiveness
> Updated Layout

- src/commands/start/index.ts
With this change I intend to ignore the linting issue of a specific unresolvable import.
> fix: ignore intended unresolvable import

- Readme.md
- src/server/src/db/knex.ts
Fix migrations running on cli command `start`
> Fixing the path for migrations when running from cli

- .gitignore
- package-lock.json
- package.json
- scripts/checkDependencies.js
- src/app/package-lock.json
- src/app/package.json
- src/server/package-lock.json
- src/server/package.json
- src/server/src/db/knex.ts
- vite.config.js
First attempt at publishing the package. Works to publish via npm currently and create tarballs for independent publishing as a cli download/install. Publishing works but uncovered an issue:
- migrations don't work with published npm #33
I ended up solving this issue with this PR as well
This solution was not ideal because I ended up having to dup dependencies from the submodules into the root module in order for the node_modules to be available on the device that installs the package. If there's a better alternative, I'm all ears. To protect against issues with this, added a script for publishing to npm that involves validating that all packages that need to be present are in the root module. Any thoughts here are appreciated
> Issue 27 cli deployment

- src/commands/start/index.ts
- Add a very basic ASCII logo and welcome message on start
- Never made ASCII art before so judge lightly.
> [Issue 36] - Added code climbers welcome message on start

- package-lock.json
- package.json
- src/server/package.json
- src/server/src/app.module.ts
The nestjs backend will deliver the built app assets at localhost:14400
> Issue 29 deliver app assets

- src/app/src/components/Home/Source/Sources.empty.tsx
- Fix the bug for adding a source in the empty state
- Do we want a different component for isEmpty here?
> Bug: Sources Empty State Add Source

- src/server/src/main.ts
- src/server/src/v1/v1.module.ts
- src/server/utils/__tests__/wakatime.util.test.ts
- src/server/utils/wakatime.util.ts
With this change I intend to add entries required for wakatime config
> Issue 81 wakatime config

- packages/app/src/App.tsx
- packages/app/src/hooks/useBrowserPreferences.ts
> [ISSUE-93] Added a way to detect browser preferences and set theme to it

- package-lock.json
- package.json
- Add the `@oclif/plugin-update` plugin. It also handles updating automatically for us.
- We need to add the s3 path in the package.json
> [Issue 100] Added @oclif/plugin-update

- Readme.md
- package-lock.json
With this change I intend to fix the build bug on mac x64 machines and update readme. Tested updates to package-lock.json on an arm64 machine as well and it works
To replicate, run these commands on a x64 mac
```
git clone https://github.com/CodeClimbersIO/cli.git && cd cli
npm i
npm run build
npx codeclimbers start server
```
> Mac x64 build bug

- packages/app/src/components/Home/Time/Time.tsx
With this change I intend to remove unused elements
> Remove unused elements

- package-lock.json
- package.json
- packages/server/src/app.module.ts
- packages/server/src/main.ts
- packages/server/src/sentry.ts
- Add Sentry logging for the API
- I am the only seat on the free tier. Happy to transfer it to someone else, or @rphovley you can replace the dsn with your own key.
> Added sentry logging

- packages/server/src/v1/activities/activities.service.ts
- Add fallbacks for some of the values in a pulse dto
> [Issue 120] pulse missing records

- package-lock.json
- packages/app/src/App.tsx
- packages/app/src/hooks/useAnalytics.ts
- packages/app/src/hooks/useBrowserPreferences.ts
- packages/app/src/hooks/useBrowserStorage.ts
- packages/app/src/routes/AppRoutes.tsx
- packages/app/src/vite-env.d.ts
- packages/app/tsconfig.json
- packages/app/vite.config.js
- Add a ga4 hook for interacting with google analytics
- Implement dnt to be respective of users that opt out
- Fix a bug around theme fallback
- Auto track page events by having a custom component in AppRoutes
- Added set value if empty param on useBrowserStorage so it persist if the value isn't interacted with by the user (useful in a case like this with the clientId UUID)
- Added `__IS_DEV__` to the vite build so we can disable analytic events in development.
> [Issue 63] Google Analytics

- packages/app/src/components/Home/Header.tsx
- packages/app/src/components/Home/Source/AddSources.tsx
- packages/app/src/components/Home/Source/Sources.tsx
- packages/app/src/components/Home/Time/CategoryChart.tsx
- packages/app/src/components/Home/Time/TimeDataChart.tsx
- packages/app/src/config/theme.ts
- packages/server/src/v1/database/__tests__/pulse.repo.test.ts
- packages/server/src/v1/database/pulse.repo.ts
With this change I intend to update the report to count in 2 minute blocks instead of 1 minute. Updated frontend theming to match designs
> Issue 126 validate data reports

- packages/server/src/app.module.ts
- packages/server/utils/node.util.ts
> update app path

- packages/server/src/assets/startup.plist.ts
With this change I intend to fix plist home path 
> Update plist home path to be dynamic

- bin/startup.js
- docs/BootupServices.md
- package-lock.json
- package.json
- packages/server/src/v1/startup/darwinStartup.service.ts
- packages/server/src/v1/startup/linuxStartup.service.ts
- packages/server/src/v1/startup/startup.util.ts
- packages/server/utils/node.util.ts
With this change I intend to convert the management of the mac services to run with the node-mac package
> Use node-mac to manage startup services

- package-lock.json
- packages/app/src/components/Home/Header.tsx
- packages/app/src/components/Home/Source/Sources.empty.tsx
- packages/app/src/utils/style/rgbAnimation.ts
- Add a reusable SX object for making RGB animated text
- Relies on https://github.com/CodeClimbersIO/cli/pull/140
https://github.com/user-attachments/assets/27ec2dac-850e-4007-8ab2-6574ef1f3386
> Issue 142 rgb text

- packages/app/src/components/Home/Source/AddSources.tsx
- packages/app/src/utils/supportedSources.ts
Trying to look at ways to improve the initial user's experience.
- Removed firefox. 
- Moved UI to use dialog and accordions. 
- Added refresh button so user can see it in sync
- Changed it from saying "connected" to the last active state
- Added links to the extensions name so the user can add them easier
> CLI: Add Sources Changes

- .gitignore
- bin/run.sh
- bin/startup.js
- package-lock.json
- package.json
- packages/server/src/v1/startup/darwinStartup.service.ts
- packages/server/utils/node.util.ts
With this change I intend to fix a node path issue for different ways to install node that lead to the startup script failing
> Issue 0 fix node path

- packages/commands/stop/index.ts
- Stopping was putting the cli into an infinite loop. 
- I don't think we should be disabling startup if they stop it, so I removed the startup service from being used here.
> BUG: CLI stop infinite loop 

- bin/run.sh
- bin/startup.js
- package-lock.json
- package.json
- packages/server/src/main.ts
- packages/server/src/v1/startup/darwinStartup.service.ts
- packages/server/utils/node.util.ts
With this change I intend to simplify startup service run process and add debug logging
> Issue 161 fix startup

- package-lock.json
- package.json
- packages/commands/start/index.ts
- packages/server/src/v1/startup/darwinStartup.service.ts
- packages/server/utils/wakatime.util.ts
With this change I intend to add clearer logging on startup
> Improve messaging in startup

- package-lock.json
- package.json
- packages/app/src/components/Home/Resources/Resources.tsx
- packages/app/src/components/Home/Source/Sources.tsx
> Issue 169 - Updated some styles

- .eslintrc.js
- .gitignore
- bin/startup.js
- package-lock.json
- packages/server/src/app.module.ts
- packages/server/src/v1/startup/startupService.factory.ts
- packages/server/src/v1/startup/windowsStartup.service.ts
- packages/server/src/v1/v1.module.ts
- packages/server/utils/node.util.ts
With this change I intend to add windows support to start commands. Had to update our node utils path commands and our startup.js as well to accommodate windows nuances.
> Issue 73 windows support

- bin/startup.js
- package-lock.json
- packages/server/commands/start/index.ts
- packages/server/commands/startup/disable.ts
- packages/server/commands/startup/enable.ts
- packages/server/commands/stop/index.ts
- packages/server/index.ts
- packages/server/src/app.module.ts
- packages/server/src/main.ts
- packages/server/src/sentry.ts
- packages/server/src/v1/startup/darwinStartup.service.ts
- packages/server/src/v1/startup/linuxStartup.service.ts
- packages/server/src/v1/startup/windowsStartup.service.ts
- packages/server/tsconfig.json
- packages/server/utils/environment.util.ts
- packages/server/utils/node.util.ts
- packages/server/utils/wakatime.util.ts
With this change I intend to fix the file paths that are broken on local development. Also did some cleanup on environment variables and fixed some logging issues I introduced
> Issue 0 file pathing and environments

- .github/workflows/bump_minor_version.yml
- .github/workflows/bump_patch_version.yml
- .github/workflows/release.yml
- Add a starting point for the release workflow.
- It will need a `NPM_TOKEN` and `GH_PAT` added to github secrets.
> Issue 162 - Publish to NPM Workflow

- docs/Troubleshooting.md
- packages/server/utils/node.util.ts
With this change I intend to start documenting troubleshooting steps
> begin documenting troubleshooting steps

- packages/app/src/api/pulse.api.ts
- packages/app/src/components/Home/Time/CategoryChart.tsx
- packages/app/src/components/common/UpdateBanner/UpdateBanner.tsx
- packages/server/src/v1/database/__tests__/pulse.repo.test.ts
- packages/server/src/v1/database/pulse.repo.ts
- packages/server/src/v1/database/queries/getLongestDayInRangeMinutes.sql
With this change I intend to fix update banner, show categorization more fully.
> New Message on Update Banner and Categorization Fixes

- packages/app/src/api/pulse.api.ts
- packages/app/src/components/Home/Time/CategoryChart.tsx
- packages/app/src/components/Home/Time/TimeDataChart.tsx
- packages/server/src/types/time.api.d.ts
- packages/server/src/v1/activities/activities.service.ts
- packages/server/src/v1/activities/pulse.controller.ts
- packages/server/src/v1/dtos/getCategoryTimeOverview.dto.ts
With this change I intend to update the time chart graph to roll over after 3 hours per category to keep some relative comparison to each other
> Time chart graphs are a percentage of 3 hours and roll over

- packages/app/src/api/keys.ts
- packages/app/src/api/pulse.api.ts
- packages/app/src/components/Home/DeepWork.tsx
- packages/app/src/components/Home/Time/Time.tsx
- packages/server/src/types/time.api.d.ts
- packages/server/src/v1/activities/activities.service.ts
- packages/server/src/v1/activities/pulse.controller.ts
- packages/server/src/v1/database/pulse.repo.ts
- packages/server/src/v1/database/queries/getDeepWork.sql
With this change I intend to add deep work time tracking to the app
> Add deep work to track focus time

- packages/app/src/components/Home/DeepWork.tsx
- packages/app/src/components/Home/Time/TimeDataChart.tsx
- packages/app/src/components/common/UpdateBanner/UpdateBanner.tsx
With this change I intend to fix deep work error when no deep work returned
> Issue 0 fix deepwork divide by zero

- package-lock.json
- package.json
- packages/app/src/App.tsx
- packages/app/src/utils/posthog.util.ts
With this change I intend to add posthog
> Add posthog

- package-lock.json
- package.json
- packages/server/src/v1/startup/darwinStartup.service.ts
- packages/server/src/v1/startup/linuxStartup.service.ts
- packages/server/src/v1/startup/startup.util.ts
- packages/server/utils/node.util.ts
With this change I intend to add linux support
> Issue 72 linux support

- .eslintrc.js
- eslint-plugin-codeclimbers/index.js
- eslint-plugin-codeclimbers/package.json
- package-lock.json
- package.json
- packages/app/src/components/Home/Header.tsx
- packages/app/src/components/Home/Resources/NewsletterForm.tsx
- packages/app/src/components/Home/Resources/Resources.tsx
- packages/app/src/components/Home/Source/AddSources.tsx
- packages/app/src/components/Home/Source/Sources.empty.tsx
- packages/app/src/components/Home/Source/Sources.loading.tsx
- packages/app/src/components/Home/Source/Sources.tsx
- packages/app/src/components/common/CodeClimbersButton.tsx
- packages/app/src/components/common/CodeClimbersIconButton.tsx
- packages/app/src/components/common/CodeSnippit/CodeSnippit.tsx
With this change I intend to add explicit event tracking for buttons and links in the app
> Add better event tracking and add linting rule for buttons

- packages/app/src/utils/posthog.util.ts
With this change I intend to update posthog
> Always create a profile for users

- packages/app/src/components/Home/InstallPage.tsx
- packages/app/src/components/common/CodeSnippit/CodeSnippit.tsx
- packages/app/src/index.css
- packages/app/src/index.html
- packages/server/utils/environment.util.ts
Fix issues with the landing page styles
> Issue 0 fix landing page

- packages/app/src/components/Home/HomePage.tsx
- packages/app/src/components/Home/InstallPage.tsx
- packages/app/src/components/common/UpdateBanner/UpdateBanner.tsx
- packages/app/src/hooks/useBrowserStorage.ts
- packages/app/src/index.html
- packages/app/src/layouts/PublicLayout.tsx
- packages/app/src/routes/AppRoutes.tsx
- packages/app/src/routes/index.tsx
With this change I intend to add install route and seo
> Add install route and seo

- packages/app/src/components/common/CodeSnippit/CodeSnippit.tsx
> Fix copy command icon

- packages/server/src/main.ts
> Add subdomains for cors

- packages/app/src/components/common/UpdateBanner/UpdateBanner.tsx
With this change I intend to fix update banner dismissing
> Fix dismissing update banner

- packages/app/src/components/Home/Source/Sources.tsx
- packages/app/src/components/common/WeeklyReportDialog.tsx
- packages/config/src/server.ts
- packages/server/src/v1/database/pulse.repo.ts
- packages/server/utils/packageJson.util.ts
With this change I intend to fix a time counting problem
> fix issue with time counting multiples of itself

- packages/app/src/extensions/SqlSandbox/SqlSandboxPage.tsx
With this change I intend to fix access issue in sql extension
> fix to sql extension
